language: python
python:
- '3.5'
- '2.7'
- '3.4'
- '3.6'
matrix:
  include:
  - python: '3.7'
    dist: xenial
install:
- pip install -e .
- pip install -r requirements-dev.txt
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
